/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jetucker_Encryptor */

#ifndef _Included_com_jetucker_Encryptor
#define _Included_com_jetucker_Encryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jetucker_Encryptor
 * Method:    Encrypt
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jetucker_Encryptor_Encrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

/*
 * Class:     com_jetucker_Encryptor
 * Method:    Decrypt
 * Signature: ([BJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jetucker_Encryptor_Decrypt
  (JNIEnv *, jobject, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
